### ISSUE TITLE
separation boundary

### ISSUE THREAD

**Issue by PangziZhang523** [oneThousand1000/HairMapper#1]
First of all, thank you for your work.
When using the separation boundary of InterfaceGAN, the gender score is 1 for boys and 0 for girls? Do I need to train a separate gender classifier to score? The hair score is trained by Resnet50 as a classifier, but do you also binarize the final score to 0 or 1?

**Comment by oneThousand1000** [comment]
> First of all, thank you for your work. When using the separation boundary of InterfaceGAN, the gender score is 1 for boys and 0 for girls? Do I need to train a separate gender classifier to score? The hair score is trained by Resnet50 as a classifier, but do you also binarize the final score to 0 or 1?


Gender score: 1 for boys and 0 for girls
Hair score: 1 for hair and 0 for bald

I have trained a hair classifier and a gender [classifier](https://github.com/oneThousand1000/HairMapper/tree/master/classifier), you can find the download link of pretrained classifiers (classification_model.pth) in the readme.

The two classifiers are trained on CelebAMask-HQ.

**Comment by PangziZhang523** [comment]
Thanks for answering.
The score you are talking about is the label for training the classifier. If so, I get it.
