### ISSUE TITLE
 Color cast in the result images

### ISSUE THREAD

**Issue by rainsoulsrx** [oneThousand1000/HairMapper#10]
Hi, Thanks for you nice work!
When I use you inference code, I notice that there are very obvious color change in some results, just as follows. But in your paper and supplyment, there is no such problem. Is there anything wrong with me? 
<img width="638" alt="image" src="https://user-images.githubusercontent.com/24955512/178209713-85c2436f-a499-425e-b8a2-a2b960262ee9.png">

**Comment by oneThousand1000** [comment]
Hi, I think maybe the Poisson Editing tries to blend the black background with the gan-generated image, and bring up a “lightened” face. The last image in Fig. 8 of suppl illustrates this problem (in that case, face shadow is blended with the gan-generated image).

You can try to use other blend methods.
![1](https://user-images.githubusercontent.com/32099648/178211512-c204ccbd-3ba6-4f69-ac29-7223f97bd5fb.PNG)

**Comment by rainsoulsrx** [comment]
Is there any other blend methods you recommend?~~

**Comment by oneThousand1000** [comment]
> Is there any other blend methods you recommend?~~

I haven't tried other methods, maybe you can take a look at [GP-GAN](https://github.com/wuhuikai/GP-GAN) and [DeepImageBlending](https://github.com/owenzlz/DeepImageBlending).

**Comment by rainsoulsrx** [comment]
> > Is there any other blend methods you recommend?~~
> 
> I haven't tried other methods, maybe you can take a look at [GP-GAN](https://github.com/wuhuikai/GP-GAN) and [DeepImageBlending](https://github.com/owenzlz/DeepImageBlending).



> > Is there any other blend methods you recommend?~~
> 
> I haven't tried other methods, maybe you can take a look at [GP-GAN](https://github.com/wuhuikai/GP-GAN) and [DeepImageBlending](https://github.com/owenzlz/DeepImageBlending).

OK，thanks~
