### ISSUE TITLE
AssertionError : Stylegan_ada

### ISSUE THREAD

**Issue by ujjawalcse** [oneThousand1000/HairMapper#11]
Hey @oneThousand1000 ,
Thanks for this amazing repo.
I was trying the given Google Colab and found an Assertion Error below,

 ```
WARNING:stylegan2_ada_generator:Load model from ../ckpts/StyleGAN2-ada-Generator.pth
WARNING:stylegan2_ada_generator:No pre-trained model will be loaded!
Initializing generator.
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-20-8b3677e0e584> in <module>
      3 data_dir = '/content/drive/MyDrive/3DAI/HairMapper/test_data'
      4 print(f'Initializing generator.')
----> 5 model = StyleGAN2adaGenerator(model_name, logger=None, truncation_psi=1.0)
      6 
      7 mapper = LevelMapper(input_dim=512).eval().cuda()

../styleGAN2_ada_model/stylegan2_ada_generator.py in __init__(self, model_name, logger, truncation_psi, randomize_noise)

../styleGAN2_ada_model/base_generator.py in __init__(self, model_name, logger)

AssertionError: 
```

And the code cell producing the above error is below,

```
model_name = 'stylegan2_ada'
latent_space_type = 'wp'
data_dir = '/content/drive/MyDrive/3DAI/HairMapper/test_data'
print(f'Initializing generator.')
model = StyleGAN2adaGenerator(model_name, logger=None, truncation_psi=1.0)

mapper = LevelMapper(input_dim=512).eval().cuda()
ckpt = torch.load('./mapper/checkpoints/final/best_model.pt')
alpha = float(ckpt['alpha']) * 1.2
mapper.load_state_dict(ckpt['state_dict'], strict=True)
kwargs = {'latent_space_type': latent_space_type}
parsingNet = get_parsingNet(save_pth='./ckpts/face_parsing.pth')
inverter = InverterRemoveHair(
        model_name,
        Generator=model,
        learning_rate=0.01,
        reconstruction_loss_weight=1.0,
        perceptual_loss_weight=5e-5,
        truncation_psi=1.0,
        logger=None
)

code_dir = os.path.join(data_dir, 'code')
origin_img_dir = os.path.join(data_dir, 'actress_imgs')
res_dir = os.path.join(data_dir, 'mapper_res')

os.makedirs(res_dir, exist_ok=True)
```

Please suggest any way to tackle this issue.
Thanks once again.

**Comment by oneThousand1000** [comment]
> Hey @oneThousand1000 , Thanks for this amazing repo. I was trying the given Google Colab and found an Assertion Error below,
> 
> ```
> WARNING:stylegan2_ada_generator:Load model from ../ckpts/StyleGAN2-ada-Generator.pth
> WARNING:stylegan2_ada_generator:No pre-trained model will be loaded!
> Initializing generator.
> ---------------------------------------------------------------------------
> AssertionError                            Traceback (most recent call last)
> <ipython-input-20-8b3677e0e584> in <module>
>      3 data_dir = '/content/drive/MyDrive/3DAI/HairMapper/test_data'
>      4 print(f'Initializing generator.')
> ----> 5 model = StyleGAN2adaGenerator(model_name, logger=None, truncation_psi=1.0)
>      6 
>      7 mapper = LevelMapper(input_dim=512).eval().cuda()
> 
> ../styleGAN2_ada_model/stylegan2_ada_generator.py in __init__(self, model_name, logger, truncation_psi, randomize_noise)
> 
> ../styleGAN2_ada_model/base_generator.py in __init__(self, model_name, logger)
> 
> AssertionError: 
> ```
> 
> And the code cell producing the above error is below,
> 
> ```
> model_name = 'stylegan2_ada'
> latent_space_type = 'wp'
> data_dir = '/content/drive/MyDrive/3DAI/HairMapper/test_data'
> print(f'Initializing generator.')
> model = StyleGAN2adaGenerator(model_name, logger=None, truncation_psi=1.0)
> 
> mapper = LevelMapper(input_dim=512).eval().cuda()
> ckpt = torch.load('./mapper/checkpoints/final/best_model.pt')
> alpha = float(ckpt['alpha']) * 1.2
> mapper.load_state_dict(ckpt['state_dict'], strict=True)
> kwargs = {'latent_space_type': latent_space_type}
> parsingNet = get_parsingNet(save_pth='./ckpts/face_parsing.pth')
> inverter = InverterRemoveHair(
>         model_name,
>         Generator=model,
>         learning_rate=0.01,
>         reconstruction_loss_weight=1.0,
>         perceptual_loss_weight=5e-5,
>         truncation_psi=1.0,
>         logger=None
> )
> 
> code_dir = os.path.join(data_dir, 'code')
> origin_img_dir = os.path.join(data_dir, 'actress_imgs')
> res_dir = os.path.join(data_dir, 'mapper_res')
> 
> os.makedirs(res_dir, exist_ok=True)
> ```
> 
> Please suggest any way to tackle this issue. Thanks once again.

Hi ujjawalcse, it seems that the stylegan2_ada_generator can not find the generator checkpoint.

Did the colab script download the pre-trained mode `./ckpts/StyleGAN2-ada-Generator.pth` successfully? Please check it.

![捕获](https://user-images.githubusercontent.com/32099648/186094152-ba445866-8f61-47d8-8224-4c439eb213f4.PNG)

**Comment by ujjawalcse** [comment]
Solved!
It was not taking the input `model_path` properly defined in the `HairMapper/styleGAN2_ada_model/model_settings.py` at line no. 26.
So, I just replaced this line with absolute model path as,
`'model_path': '/content/HairMapper/ckpts/StyleGAN2-ada-Generator.pth'`
