### ISSUE TITLE
Output Color is changed

### ISSUE THREAD

**Issue by ujjawalcse** [oneThousand1000/HairMapper#12]
Hey @oneThousand1000 ,
Sorry for bothering, But the result i'm getting has a lot differences between color map.
Here is one reference,
![aish_color_change](https://user-images.githubusercontent.com/32773256/186136139-bc555429-f017-48ae-b460-6a5ae19bbd11.png)

I though it's due to RGB image mode so i checked it by converting into BGR, But that's also not matching to the original image color and light.

Any suggestions?

**Comment by oneThousand1000** [comment]
Hi ujjawalcse, could you upload your input image? (Please upload a zip file)

**Comment by ujjawalcse** [comment]
yaa sure,
[temp.zip](https://github.com/oneThousand1000/HairMapper/files/9402232/temp.zip)

**Comment by oneThousand1000** [comment]
I ran the colab script using the images you uploaded, but everything is Ok.

Did you put the original images to 'HairMapper/test_data/origin'? And did you run all the code instead of skipping or modifying something?

![下载 (1)](https://user-images.githubusercontent.com/32099648/186154014-e418d0b2-2fa5-4d9a-b237-fa5afa2bbad9.png)
![下载](https://user-images.githubusercontent.com/32099648/186154021-50d23acf-581a-4b52-a6ad-7b3bc5418ec1.png)

**Comment by ujjawalcse** [comment]
yaa, actually, the 'test_data' is in my drive,
Also I have changed the path wherever required,

![HairMapper_dir](https://user-images.githubusercontent.com/32773256/186155413-3e458f77-23f4-4b8f-a7ae-dcc94dd5534e.png)
 
'aligned_actress_images' contains the aligned images
'code' contains the *.npy for each of them.

Is anything else required?

**Comment by oneThousand1000** [comment]
Did you modify this line in Step 5: Run HairMaper?
`edited_img = outputs['image'][0][:, :, ::-1]`

After I changing it into `edited_img = outputs['image'][0]`, I got the same strange results as yours.

Please make sure the color space is converted before inputing the edited_img to cv2.seamlessClone, like:

'''
edited_img = outputs['image'][0][:, :, ::-1]

#do some thing here

mixed_clone = cv2.seamlessClone(origin_img, edited_img, face_mask[:, :, 0], center, cv2.NORMAL_CLONE)
'''

**Comment by ujjawalcse** [comment]
Ohh okay, That may be the issue ,that is converted by me.
I'm just doing that and let you know.

**Comment by ujjawalcse** [comment]
Got it. 
Thank you very much @oneThousand1000  for your humble and quick responses.
