### ISSUE TITLE
Resize error for face parsing mask

### ISSUE THREAD

**Issue by Robin970822** [oneThousand1000/HairMapper#13]
Hi, all cv2.resize usages for face parsing mask are not right (height x width), should be (width x height) as cv2.resize(hair_mask,(img_shape[1], img_shape[0]))
https://github.com/oneThousand1000/HairMapper/blob/db8550efeea2aa5856e4bc129483cc7752b40b07/classifier/src/feature_extractor/hair_mask_extractor.py#L209

**Comment by oneThousand1000** [comment]
> Hi, all cv2.resize usages for face parsing mask are not right (height x width), should be (width x height) as cv2.resize(hair_mask,(img_shape[1], img_shape[0]))
> 
> https://github.com/oneThousand1000/HairMapper/blob/db8550efeea2aa5856e4bc129483cc7752b40b07/classifier/src/feature_extractor/hair_mask_extractor.py#L209

Thanks for pointing it out! I'll fix it.

Actually, img_shape[0] is equal to img_shape[1] so this mistake will not influence the results.

**Comment by oneThousand1000** [comment]
This issue have been fixed.

**Comment by Robin970822** [comment]
I tried some random images with different widths and heights and found it :).
