### ISSUE TITLE
id_loss is not active

### ISSUE THREAD

**Issue by ysnylmzz** [oneThousand1000/HairMapper#16]
Hi, Thanks for your nice work!

I would like to ask why did u comment out id_loss during optimization (diffuse). Are Pixel-wise reconstruction loss and Perceptual loss enough to preserve identity?

**Comment by oneThousand1000** [comment]
Yes, you are right!
We find that the existing 2 losses is enough to get ideal results, so we remove the id loss to accelerate training.

**Comment by ysnylmzz** [comment]
I see, thank you.
