### ISSUE TITLE
Which model is being used to test 3D face reconstruction result

### ISSUE THREAD

**Issue by ujjawalcse** [oneThousand1000/HairMapper#17]
Hey @oneThousand1000 ,
As you suggested, 3D face reconstruction should be improved.
Can you tell which model you used to test the 3D face reconstruction?
Also, suggest the steps to be used if possible.

Thanks

**Comment by oneThousand1000** [comment]
Hi! We used the [GANFit](https://github.com/barisgecer/GANFit) model. However, the reconstruction code is not publicized, so we just sent the author some images and asked him to generate results for us.

**Comment by ujjawalcse** [comment]
ohh! okay @oneThousand1000.
