### ISSUE TITLE
About video hair removing

### ISSUE THREAD

**Issue by Dratlan** [oneThousand1000/HairMapper#23]
I've tried this code for video hair removing, the results is not so good(with flicker and discontinuities). Do you have some suggestions?

**Comment by oneThousand1000** [comment]
Maybe transferring our method to 3D-aware model could be helpful (but it needs some experiments and algorithm design, it's not straightforward and easy)

**Comment by Dratlan** [comment]
Thanks for your suggestions, I'll try for it

**Comment by Dratlan** [comment]
![微信图片_20240722161134](https://github.com/user-attachments/assets/b934331c-aca2-44a1-a73d-7e9442f721f6)
and another question In Fig.5, how can I get blended image(bottom right) from synthetic image(bottom middle)? the blurring mask around the face is not needed for me.

**Comment by oneThousand1000** [comment]
The Blending is based on Poisson Editing

**Comment by Dratlan** [comment]
Thanks, is there a code implementation in this repository?

**Comment by oneThousand1000** [comment]
> Thanks, is there a code implementation in this repository?

https://github.com/oneThousand1000/HairMapper/blob/ec4f31afe116878eedc0a761a85dcdbe76436753/main_mapper.py#L150

**Comment by Dratlan** [comment]
Thanks for your quickly reply
