### ISSUE TITLE
Is it possible to provide online demo or obtain test results by https request？

### ISSUE THREAD

**Issue by SeaRecluse** [oneThousand1000/HairMapper#4]
Your project needs the support of more additional models, could you consider using the online demo for testing?

**Comment by oneThousand1000** [comment]
> Your project needs the support of more additional models, could you consider using the online demo for testing?

You can use the [colab notebook demo](https://colab.research.google.com/github/oneThousand1000/HairMapper/blob/master/notebooks/HairMapper.ipynb).
