### ISSUE TITLE
How to blend other hair style?

### ISSUE THREAD

**Issue by YuhaoShan2018** [oneThousand1000/HairMapper#6]
Hi researchers of HairMapper,
Could you please give me some hints on how to blend other hairstyles like the Figure 1  shown on the front page of the paper?
thank you !

**Comment by oneThousand1000** [comment]
> Hi researchers of HairMapper, Could you please give me some hints on how to blend other hairstyles like the Figure 1 shown on the front page of the paper? thank you !

Hi YuhaoShan~
Please refer to #5, I have uploaded an exemplar code.

**Comment by oneThousand1000** [comment]
I'll close the issue~ 
Please let me know if you require any other assistance.
