### ISSUE TITLE
About the latent space of stylegan2 and stylegan2-ada.

### ISSUE THREAD

**Issue by gzhhhere** [oneThousand1000/HairMapper#7]
Thank you for your outstanding work!
I noticed that e4e is trained on stylegan2 and the bald latent code output by hairMapper feeds into stylegan2-ada. Are the potential spaces of these two generators the same, or does hairMapper implicitly do the migration of the two potential spaces? Can you please tell me why you are using stylegan2- ada instead of stylegan2?
I ask because I want to test the pre-trained hairMapper directly on the stylegan2 generator, however, I haven't gotten around to trying it yet.

**Comment by oneThousand1000** [comment]
> Thank you for your outstanding work!
> I noticed that e4e is trained on stylegan2 and the bald latent code output by hairMapper feeds into stylegan2-ada. Are the potential spaces of these two generators the same, or does hairMapper implicitly do the migration of the two potential spaces? Can you please tell me why you are using stylegan2- ada instead of stylegan2?
> I ask because I want to test the pre-trained hairMapper directly on the stylegan2 generator, however, I haven't gotten around to trying it yet.

Hi, the stylegan2-ada is full support for network pickles produced by [StyleGAN](https://github.com/NVlabs/stylegan) and [StyleGAN2](https://github.com/NVlabs/stylegan2). We use the pretrained stylegan2 model in our work. You can test the pre-trained hairMapper directly on the stylegan2 generator!

**Comment by gzhhhere** [comment]
Thank you very much, your guidance helped me to remove a lot of doubts.
As a beginner, I'd like to double-check what you mean. You used the [stylegan2-ffhq-config-f.pkl](https://github.com/NVlabs/stylegan2), an original stylegan2 weight.
And Could you please elaborate a little on how you got the "StyleGAN2-ada-Generator.pth" in your README.md, because I noticed that your "StyleGAN2-ada-Generator.pth " and the official "stylegan2-ffhq-config-f.pkl" from Nvidia are different in file format and size.
Thanks again for your patience and kindness!

**Comment by oneThousand1000** [comment]
> Thank you very much, your guidance helped me to remove a lot of doubts. As a beginner, I'd like to double-check what you mean. You used the [stylegan2-ffhq-config-f.pkl](https://github.com/NVlabs/stylegan2), an original stylegan2 weight. And Could you please elaborate a little on how you got the "StyleGAN2-ada-Generator.pth" in your README.md, because I noticed that your "StyleGAN2-ada-Generator.pth " and the official "stylegan2-ffhq-config-f.pkl" from Nvidia are different in file format and size. Thanks again for your patience and kindness!

Yes, you are right. I used the [stylegan2-ffhq-config-f.pkl](https://github.com/NVlabs/stylegan2), but I extracted the parameters of  stylegan2-ffhq-config-f.pkl and save them as StyleGAN2-ada-Generator.pth, it is actually the same parameters that in the original stylegan2. I apologize for the ambiguous rename!

I have modified the framework of stylegan-ada (as I mentioned in readme, "We modified the stylegan-ada pytorch version to output latent codes in Z, W, W+ and StyleSpace more conveniently.").

But I find that the .pkl model saves the entire network framework, I can't use my own modified version of the framework if I load the .pkl model (I used 'legacy.load_network_pkl' to load pkl). Maybe I have loaded the pre-trained model in the wrong way...

You can input the same latent code to the stylegan2-ada model in my code and the official stylegan2 code to test whether they output the same image (in my experiment, they have the same output).

**Comment by gzhhhere** [comment]
Thank you for your information!
I will provide timely feedback with useful information in the later experiments.

**Comment by oneThousand1000** [comment]
> Thank you for your information! I will provide timely feedback with useful information in the later experiments.

Thanks for pointing this out. I will update the description of "StyleGAN2-ada-Generator.pth" in my README.

**Comment by oneThousand1000** [comment]
Hi gzhhhere. I input the same latent code in Z latent space (with truncation_psi = 1.0 ), they actually output the same image.
I uploaded the test latent code and output images:  [out.zip](https://github.com/oneThousand1000/HairMapper/files/8695128/out.zip)

`seed0085.npy`:  latent code in Z latent space
`seed0085.png`: the output image of the official [stylegan2-ada-pytorch](https://github.com/NVlabs/stylegan2-ada-pytorch), using the pkl model stylegan2-ffhq-1024x1024.pkl.
`seed0085_my_ada.png`: the output image of my [stylegan2-ada code ](https://github.com/oneThousand1000/HairMapper/tree/master/styleGAN2_ada_model), using the pth model StyleGAN2-ada-Generator.pth.


Please let me know if you require any other assistance.

**Comment by gzhhhere** [comment]
I have no more questions, thank you for your reply.
