### ISSUE TITLE
About 'keeping the rest of the layers unchanged'.

### ISSUE THREAD

**Issue by gzhhhere** [oneThousand1000/HairMapper#8]
Hi!
In reading your code, I found a detail that may not correspond to the paper. This detail is insignificant, but if possible, I still want to know if you have unique thinking.

Specifically, in '.\styleGAN2_ada_model\stylegan2_ada_generator.py', near line 384, 
![image](https://user-images.githubusercontent.com/43848061/169075277-0910c6e4-6c43-4d6e-8742-3993b242c11b.png)
the [7-17] layers (starting from 0) of the edited W + are replaced by the original W +.  That is, only the first 7 layers of W + are ''obviously'' manipulated. 

Is this inconsistent with the first 8 layers of change mentioned in the paper, or do I make a low-level code understanding mistake?

Again, this is insignificant. I just want to know if you have a unique understanding and whether the open-source pre-trained HairMapper is also trained in this way.

**Comment by oneThousand1000** [comment]
> Hi! In reading your code, I found a detail that may not correspond to the paper. This detail is insignificant, but if possible, I still want to know if you have unique thinking.
> 
> Specifically, in '.\styleGAN2_ada_model\stylegan2_ada_generator.py', near line 384, ![image](https://user-images.githubusercontent.com/43848061/169075277-0910c6e4-6c43-4d6e-8742-3993b242c11b.png) the [7-17] layers (starting from 0) of the edited W + are replaced by the original W +. That is, only the first 7 layers of W + are ''obviously'' manipulated.
> 
> Is this inconsistent with the first 8 layers of change mentioned in the paper, or do I make a low-level code understanding mistake?
> 
> Again, this is insignificant. I just want to know if you have a unique understanding and whether the open-source pre-trained HairMapper is also trained in this way.

Sorry for the inaccurate parameter in code. 
In fact, the author of stylegan divide the 18 layers of latent code into 3 level: [0,4) for coarse (high-level aspects such as pose, hairstyle, face shape ....), [4,8) for the middle (smaller scale facial features) and [8-18) for fine (mainly the color scheme and microstructure). More details can be found in "A Style-Based Generator Architecture for Generative Adversarial Networks", page 4.

So that in paper, we propose to manipulate the first 8 layers (coarse and middle), and preserve the fine styles.

**Comment by oneThousand1000** [comment]
Moreover, I think manipulating the first 8 layers or 7 layers won't affect the results too much, because such a separation (coarse, middle and fine) is not so strict.
(As you can see in our pre-trained model, most of the fine styles are preserved.)

**Comment by gzhhhere** [comment]
I understood, thank you for your reply.
